-- GENERATED by scripts/build_name_filter.mjs. Do not edit: change the lists
-- there and re-run it, which rewrites this file AND the page's own check in
-- index.html together, so the two can never disagree.
--
-- No profanity in a display name (real-user rule, 6 Oct: "make sure people
-- can't sign up with an obvious profanity ridden name"). The page refuses it
-- first, with a message; this is the same rule in the database, for a name
-- written around the page. All create-or-replace: running it again is safe.
--
-- Only a NEW or CHANGED name is judged: a trigger, deliberately not a CHECK
-- constraint, which runs on every update of the row and would stop an account
-- already holding a refused name from saving its colour or its settings.

-- Accents dropped, Hangul put back together, look-alike Cyrillic and Greek
-- read as Latin, lowercase. nameFilterFold() on the page, step for step.
create or replace function public.display_name_fold(s text)
returns text
language sql
immutable
set search_path = ''
as $$
  select lower(translate(
    normalize(regexp_replace(normalize(s, NFKD), '[\u0300-\u036f]', '', 'g'), NFC),
    'АВЕКМНОРСТХаеорсухкмітѕјԁһΑΒΕΗΙΚΜΝΟΡΤΥΧΖαεικνορτυχÆØ',
    'abekmhopctxaeopcyxkmitsjdhabehikmnoptyxzaeikvoptuxæø'
  ))
$$;

-- isCleanDisplayName() on the page, inverted: true when the name is refused.
create or replace function public.display_name_blocked(dname text)
returns boolean
language plpgsql
immutable
set search_path = ''
as $$
declare
  folded text := left(public.display_name_fold(coalesce(dname, '')), 40);
  form text;
  words text[];
  runs text[];
  w text;
  last text;
  x text;
  sq boolean;
begin
  foreach form in array array[
    regexp_replace(folded, '[0-9]', '', 'g'),
    regexp_replace(translate(folded, '01345789', 'oieastbg'), '[0-9]', '', 'g')
  ] loop
    words := array(select t from regexp_split_to_table(form, '[ ''-]+') t where t <> '');
    runs := '{}';
    last := null;
    foreach w in array words loop
      if cardinality(runs) > 0 and (char_length(w) = 1 or char_length(last) = 1) then
        runs[cardinality(runs)] := runs[cardinality(runs)] || w;
      else
        runs := runs || w;
      end if;
      last := w;
    end loop;
    foreach sq in array array[false, true] loop
      foreach x in array runs loop
        if sq then x := regexp_replace(x, '(.)\1+', '\1', 'g'); end if;
        if (not sq and regexp_replace(x, '(scunthorpe|nigeria)', '_', 'g') ~ '(fuck|fvck|fck|cunt|bitch|biatch|whore|nigger|nigga|faggot|retard|dildo|jizz|pussy|bollock|asshole|arsehole|blowjob|handjob|rimjob|cocksuck|wanker|wanking|slutty|titty|titties|vagina|scrotum|testicle|hitler|pedophile|paedophile|wetback|tranny|skank|bullshit|horseshit|dipshit|shitty|shithead|pornstar|pornhub|buttplug|butthole|deepthroat|cumshot|gangbang|masturbat|killyourself|sibal|ssibal|sibbal|ssibbal|shibal|byungsin|byungshin|byeongsin|byeongshin|gaesaekki|gaesaeki|gaesekki|jiral|fisse|kneppe|spasser|perker|kælling|씨발|씨빨|씨팔|시발|시빨|씨바|십새|씹|좆|좃|존나|병신|븅신|빙신|병쉰|개새끼|개새기|개색기|개색끼|개세끼|개쌔끼|새끼|쌔끼|지랄|미친놈|미친년|니애미|느금마|니기미|엠창|창녀|섹스|걸레|쌍년|썅|후장|딸딸이|염병|ᄉᄇ|ᄊᄇ|ᄇᄉ|ᄡ|ᄌᄅ|ᄌᄂ|ᄆᄎ|ᄉᄁ)')
           or (sq and regexp_replace(x, '(scunthorpe|nigeria)', '_', 'g') ~ '(fuck|fvck|fck|cunt|bitch|biatch|whore|niger|fagot|retard|dildo|bolock|ashole|arsehole|blowjob|handjob|rimjob|cocksuck|wanker|wanking|sluty|tities|vagina|scrotum|testicle|hitler|pedophile|paedophile|wetback|skank|bulshit|horseshit|dipshit|shity|shithead|pornstar|pornhub|butplug|buthole|depthroat|cumshot|gangbang|masturbat|kilyourself|sibal|shibal|byungsin|byungshin|byeongsin|byeongshin|gaesaeki|gaeseki|jiral|knepe|spaser|perker|kæling|씨발|씨빨|씨팔|시발|시빨|씨바|십새|씹|좆|좃|존나|병신|븅신|빙신|병쉰|개새끼|개새기|개색기|개색끼|개세끼|개쌔끼|새끼|쌔끼|지랄|미친놈|미친년|니애미|느금마|니기미|엠창|창녀|섹스|걸레|쌍년|썅|후장|염병|ᄉᄇ|ᄊᄇ|ᄇᄉ|ᄡ|ᄌᄅ|ᄌᄂ|ᄆᄎ|ᄉᄁ)') then
          return true;
        end if;
      end loop;
      foreach x in array (array[array_to_string(words, '')] || words || runs) loop
        if sq then x := regexp_replace(x, '(.)\1+', '\1', 'g'); end if;
        if (not sq and x ~ '^(big|huge|fat|small|tiny|little|my|your|mr|mrs|dumb|stupid|jack|hairy|smelly|sweaty|lick|suck|eat|kiss|stor|lille|fede|dum|din|min|bøsse|ass|arse|anal|anus|boob|boobs|cock|cum|dick|fag|kike|chink|spic|gook|coon|dyke|nazi|piss|porn|prick|rape|rapist|pedo|semen|sex|shit|slut|tits|penis|wank|clit|douche|bastard|twat|kkk|phuck|pik|røv|lort|hore|luder|neger|pis|kusse|ᅩ|보지|자지)*(ass|arse|anal|anus|boob|boobs|cock|cum|dick|fag|kike|chink|spic|gook|coon|dyke|nazi|piss|porn|prick|rape|rapist|pedo|semen|sex|shit|slut|tits|penis|wank|clit|douche|bastard|twat|kkk|phuck|pik|røv|lort|hore|luder|neger|pis|kusse|ᅩ|보지|자지)(head|face|hole|wipe|hat|bag|lord|king|master|sucker|licker|eater|lover|boy|girl|s|hoved|fjæs|hul|ansigt|unge|ass|arse|anal|anus|boob|boobs|cock|cum|dick|fag|kike|chink|spic|gook|coon|dyke|nazi|piss|porn|prick|rape|rapist|pedo|semen|sex|shit|slut|tits|penis|wank|clit|douche|bastard|twat|kkk|phuck|pik|røv|lort|hore|luder|neger|pis|kusse|ᅩ|보지|자지)*$')
           or (sq and x ~ '^(big|huge|fat|smal|tiny|litle|my|your|mr|mrs|dumb|stupid|jack|hairy|smely|sweaty|lick|suck|eat|kis|stor|lile|fede|dum|din|min|bøse|arse|anal|anus|cock|cum|dick|fag|kike|chink|spic|dyke|nazi|porn|prick|rape|rapist|pedo|semen|sex|shit|slut|tits|penis|wank|clit|douche|bastard|twat|phuck|pik|røv|lort|hore|luder|neger|pis|ᅩ|보지|자지)*(arse|anal|anus|cock|cum|dick|fag|kike|chink|spic|dyke|nazi|porn|prick|rape|rapist|pedo|semen|sex|shit|slut|tits|penis|wank|clit|douche|bastard|twat|phuck|pik|røv|lort|hore|luder|neger|pis|ᅩ|보지|자지)(head|face|hole|wipe|hat|bag|lord|king|master|sucker|licker|eater|lover|boy|girl|s|hoved|fjæs|hul|ansigt|unge|arse|anal|anus|cock|cum|dick|fag|kike|chink|spic|dyke|nazi|porn|prick|rape|rapist|pedo|semen|sex|shit|slut|tits|penis|wank|clit|douche|bastard|twat|phuck|pik|røv|lort|hore|luder|neger|pis|ᅩ|보지|자지)*$') then
          return true;
        end if;
      end loop;
    end loop;
  end loop;
  return exists (
    select 1 from regexp_split_to_table(lower(normalize(coalesce(dname, ''), NFC)), '[ ''-]+') t
    where t = any(array['địt', 'đụ', 'lồn', 'cặc', 'buồi', 'đĩ', 'đéo', 'đm', 'đmm', 'đcm', 'dcm', 'vcl', 'vkl', 'clm', 'cmm'])
  );
end;
$$;

-- 23514 is a check violation; the message is what the page would show.
create or replace function public.profiles_display_name_clean()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'UPDATE' and new.display_name is not distinct from old.display_name then
    return new;
  end if;
  if public.display_name_blocked(new.display_name) then
    raise exception 'display_name_not_allowed' using errcode = '23514';
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_display_name_clean on public.profiles;
create trigger profiles_display_name_clean
  before insert or update of display_name on public.profiles
  for each row execute function public.profiles_display_name_clean();
