-- ============================================================================
-- Push notifications to a phone (Web Push), as a THIRD channel beside the
-- email and in-app ones notification_bell_migration.sql set up.
--
-- Every notification this app sends already lands as a row in
-- `notifications` (reminders, Yonsei board, invite accepted, the recaps,
-- system notices), so push hangs off that one table: an AFTER INSERT trigger
-- hands the new row's id to the `send-push` edge function, which sends it to
-- every device its owner has switched push on for. One trigger covers every
-- type, present and future.
--
-- Two consequences worth knowing:
--   * A push follows the bell. A type whose in-app channel is off never
--     writes a row, so it never pushes either; the settings UI greys the push
--     box out in that case rather than offering a switch that does nothing.
--   * The keys are made BY THE SERVER. The VAPID key pair is generated by the
--     edge function the first time it is asked for it, and the secret the
--     trigger authenticates with is generated right here in SQL, so no key
--     ever passes through a person, a chat or a commit. The public half is
--     served to the app on request.
--
-- Safe to re-run.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- One row of server-only configuration. RLS on with no policies, and no
-- grants to the client roles: only the service role (the edge function) and
-- SECURITY DEFINER functions can read it.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS push_config (
  id smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  vapid_public text,
  vapid_private_jwk jsonb,
  webhook_secret text NOT NULL DEFAULT encode(extensions.gen_random_bytes(32), 'hex'),
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE push_config ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON push_config FROM anon, authenticated;
INSERT INTO push_config (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- One row per device that has push switched on. The endpoint is the device's
-- own address at its push service (Apple, Google, Mozilla); p256dh and auth
-- are the keys the message is encrypted to.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS push_subscriptions (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  endpoint text NOT NULL UNIQUE,
  p256dh text NOT NULL,
  auth text NOT NULL,
  user_agent text,
  created_at timestamptz NOT NULL DEFAULT now(),
  last_success_at timestamptz
);
CREATE INDEX IF NOT EXISTS push_subscriptions_user_idx ON push_subscriptions(user_id);
ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "push_subscriptions_select_own" ON push_subscriptions;
CREATE POLICY "push_subscriptions_select_own" ON push_subscriptions FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());
-- No INSERT/UPDATE/DELETE policies: writes go through the two functions
-- below, because a device changing hands has to move a row that belongs to
-- somebody else, which a plain RLS-scoped write cannot do.

-- A device belongs to whoever switched push on on it LAST. The endpoint is
-- only known to the device itself, so holding it is the proof of being there.
CREATE OR REPLACE FUNCTION register_push_subscription(p_endpoint text, p_p256dh text, p_auth text, p_user_agent text DEFAULT NULL)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'not signed in';
  END IF;
  DELETE FROM push_subscriptions WHERE endpoint = p_endpoint AND user_id <> auth.uid();
  INSERT INTO push_subscriptions (user_id, endpoint, p256dh, auth, user_agent)
  VALUES (auth.uid(), p_endpoint, p_p256dh, p_auth, p_user_agent)
  ON CONFLICT (endpoint) DO UPDATE
    SET p256dh = excluded.p256dh, auth = excluded.auth, user_agent = excluded.user_agent;
END;
$$;
REVOKE EXECUTE ON FUNCTION register_push_subscription(text, text, text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION register_push_subscription(text, text, text, text) TO authenticated;

CREATE OR REPLACE FUNCTION unregister_push_subscription(p_endpoint text)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  DELETE FROM push_subscriptions WHERE endpoint = p_endpoint AND user_id = auth.uid();
$$;
REVOKE EXECUTE ON FUNCTION unregister_push_subscription(text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION unregister_push_subscription(text) TO authenticated;

-- ---------------------------------------------------------------------------
-- The per-type channel choice gains a push column. Default TRUE, like the
-- other two: the device-level switch is what opts a person in, and this only
-- narrows which types reach the phone once it is on.
-- ---------------------------------------------------------------------------
ALTER TABLE notification_prefs ADD COLUMN IF NOT EXISTS push boolean NOT NULL DEFAULT true;

CREATE OR REPLACE FUNCTION wants_push_notification(target_user_id uuid, ntype text)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE((SELECT push FROM notification_prefs WHERE user_id = target_user_id AND type = ntype), true);
$$;

-- The three-argument version has to go rather than sit beside a four-argument
-- one with a default: PostgREST cannot choose between the two for a call that
-- names three arguments, which is every call the current app makes. With only
-- this one left, those calls still resolve, and p_push NULL leaves push alone.
DROP FUNCTION IF EXISTS set_notification_pref(text, boolean, boolean);
CREATE OR REPLACE FUNCTION set_notification_pref(ntype text, p_email boolean, p_in_app boolean, p_push boolean DEFAULT NULL)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO notification_prefs(user_id, type, email, in_app, push)
  VALUES (auth.uid(), ntype, p_email, p_in_app, COALESCE(p_push, true))
  ON CONFLICT (user_id, type) DO UPDATE
    SET email = excluded.email,
        in_app = excluded.in_app,
        push = COALESCE(p_push, notification_prefs.push);
END;
$$;
REVOKE EXECUTE ON FUNCTION set_notification_pref(text, boolean, boolean, boolean) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION set_notification_pref(text, boolean, boolean, boolean) TO authenticated;

-- ---------------------------------------------------------------------------
-- The trigger. pg_net queues the request and sends it after the inserting
-- transaction commits, so a slow push service never holds up a reminder run.
-- It returns early for anyone with no device registered, which is almost
-- everyone almost always, so no request is made for them at all.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION notify_push_on_notification()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  secret text;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM push_subscriptions WHERE user_id = NEW.user_id) THEN
    RETURN NEW;
  END IF;
  IF NOT wants_push_notification(NEW.user_id, NEW.type) THEN
    RETURN NEW;
  END IF;
  SELECT webhook_secret INTO secret FROM push_config WHERE id = 1;
  IF secret IS NULL THEN
    RETURN NEW;
  END IF;
  PERFORM net.http_post(
    url := 'https://kbqwitmxpmkueryjsyip.supabase.co/functions/v1/send-push',
    headers := jsonb_build_object('Content-Type', 'application/json', 'x-push-secret', secret),
    body := jsonb_build_object('notification_id', NEW.id)
  );
  RETURN NEW;
EXCEPTION WHEN OTHERS THEN
  -- A push must never be able to stop the notification itself landing.
  RAISE WARNING 'push enqueue failed for notification %: %', NEW.id, SQLERRM;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS notifications_push ON notifications;
CREATE TRIGGER notifications_push
  AFTER INSERT ON notifications
  FOR EACH ROW EXECUTE FUNCTION notify_push_on_notification();

-- ---------------------------------------------------------------------------
-- Push alone, for the recaps. Their email and in-app switches live on the
-- profile (notify_daily_recap_inapp and friends), not in notification_prefs,
-- so set_notification_pref above has nothing true to write for them. This
-- touches the push column and nothing else; a row it creates takes the
-- table's own defaults for the other two, which is what no row meant anyway.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_notification_push(ntype text, p_push boolean)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO notification_prefs(user_id, type, push)
  VALUES (auth.uid(), ntype, p_push)
  ON CONFLICT (user_id, type) DO UPDATE SET push = excluded.push;
END;
$$;
REVOKE EXECUTE ON FUNCTION set_notification_push(text, boolean) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION set_notification_push(text, boolean) TO authenticated;
