-- Migration: add stable display number + TOPIK-grammar flag to grammar_points
ALTER TABLE grammar_points ADD COLUMN IF NOT EXISTS number integer;
ALTER TABLE grammar_points ADD COLUMN IF NOT EXISTS topik boolean NOT NULL DEFAULT false;

UPDATE grammar_points AS g
SET number = v.number, topik = v.topik
FROM (VALUES
  ('아무리-기로서니', 1, true),
  ('으-련만-으-련마는', 2, true),
  ('으-ㄹ-듯하다', 3, false),
  ('으-ㄹ-리가-없다', 4, true),
  ('으-ㄹ-수밖에-없다', 5, true),
  ('으-ㄹ-정도로', 6, true),
  ('으-ㄹ걸-요', 7, true),
  ('으-ㄹ까-하다', 8, true),
  ('으-ㄹ수록', 9, false),
  ('으-ㄹ지도-모르다', 10, true),
  ('으-나-마나', 11, true),
  ('으-랴-으-랴', 12, false),
  ('으-려고', 13, false),
  ('으-려나-보다', 14, false),
  ('으-려다가', 15, true),
  ('으-려던-참이다', 16, true),
  ('으-려면', 17, false),
  ('으-로서-으-로써', 18, true),
  ('으-리라-고', 19, false),
  ('으-면-몰라도', 20, false),
  ('으-면서', 21, false),
  ('이-나마', 22, true),
  ('ㄴ-는다기보다-는', 23, true),
  ('거나', 24, false),
  ('거니와', 25, true),
  ('거든-요', 26, true),
  ('건만-건마는', 27, false),
  ('게', 28, false),
  ('게-되다', 29, true),
  ('고-나서', 30, true),
  ('고-말다', 31, true),
  ('고-해서', 32, false),
  ('고-요', 33, false),
  ('고도', 34, true),
  ('고말고-요', 35, false),
  ('고서야-아-어서야', 36, true),
  ('고자-하다', 37, false),
  ('곤-하다', 38, true),
  ('기-나름이다-n-나름이다', 39, true),
  ('기-마련이다', 40, true),
  ('기-일쑤이다', 41, true),
  ('기가-무섭게', 42, false),
  ('기는요', 43, true),
  ('기는커녕', 44, true),
  ('기로-하다', 45, true),
  ('기에', 46, false),
  ('기에는', 47, false),
  ('긴-나-봐요', 48, false),
  ('길래', 49, false),
  ('느니-차라리', 50, false),
  ('느라고', 51, true),
  ('는-감이-있다', 52, false),
  ('는-길에', 53, false),
  ('는-대로', 54, true),
  ('는-대신-에', 55, true),
  ('는-데', 56, false),
  ('는-데다가', 57, true),
  ('는-둥-마는-둥-하다', 58, true),
  ('는-바람에', 59, true),
  ('는-반면-에', 60, true),
  ('는-셈-치다-ㄴ-는다고-치다', 61, true),
  ('는-수가-있다', 62, false),
  ('는-탓에-탓이다', 63, true),
  ('는-편이다', 64, true),
  ('는-한', 65, false),
  ('는-은-ㄴ-모양이다', 66, true),
  ('는-ㄴ-셈이다', 67, true),
  ('는-ㄴ-다-싶다', 68, true),
  ('는-ㄴ다는-것이', 69, false),
  ('는-은-법이다', 70, true),
  ('는-은-줄-모르다-알다', 71, true),
  ('는-은-ㄴ-을-ㄹ-듯-이', 72, true),
  ('는가-은-ㄴ가-하면', 73, true),
  ('는걸요-으-ㄴ걸요', 74, false),
  ('는지-은지-ㄴ지', 75, false),
  ('다-가-보면', 76, true),
  ('다가는', 77, false),
  ('다니-이-라니', 78, true),
  ('다시피-하다', 79, true),
  ('더니', 80, true),
  ('더라고-요', 81, true),
  ('더라도', 82, true),
  ('던', 83, false),
  ('던데요', 84, true),
  ('도록', 85, true),
  ('되', 86, true),
  ('든지', 87, true),
  ('마저-도', 88, true),
  ('만-못하다', 89, false),
  ('만-하다', 90, false),
  ('만에', 91, false),
  ('아-어-대다', 92, true),
  ('아-어-보니-까-고-보니-까', 93, true),
  ('아-어-있다', 94, true),
  ('아-어-여-놓다-두다', 95, true),
  ('아-어-여-버리다', 96, false),
  ('아-어다가', 97, false),
  ('아-어도', 98, false),
  ('았-었-였더니', 99, true),
  ('았-었-였더라면', 100, false),
  ('았-었으면-하다', 101, false),
  ('에-따라-서', 102, true),
  ('에다가', 103, true),
  ('으라고-라고', 104, false),
  ('은-ㄴ-채-로', 105, true),
  ('을-ㄹ-뻔하다', 106, true),
  ('을-ㄹ-뿐-만-아니라', 107, true),
  ('을-ㄹ-뿐이다', 108, false),
  ('을-ㄹ-수가-있어야지-요', 109, false),
  ('을-ㄹ-줄만-알았지', 110, false),
  ('을-ㄹ까-봐', 111, true),
  ('을까-나-지-싶다', 112, false),
  ('을락-말락-하다', 113, false),
  ('음으로써', 114, false),
  ('이야말로', 115, true),
  ('이자', 116, false),
  ('자마자', 117, true),
  ('조차', 118, true),
  ('치고-는', 119, true),
  ('간접화법-축약형-abbreviated-indirect-speech', 120, true),
  ('같아선-같아서는', 121, false),
  ('사동-causative-voice', 122, true),
  ('피동-passive-voice', 123, true)
) AS v(id, number, topik)
WHERE g.id = v.id;

-- Optional: enforce number uniqueness/not-null once populated
ALTER TABLE grammar_points ALTER COLUMN number SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS grammar_points_number_idx ON grammar_points(number);
